### ISSUE TITLE
Memory solution speeds up array processing!

### ISSUE THREAD

**Issue by SanbiVN** [cristianbuse/VBA-ArrayTools#1]
Hi @cristianbuse!

You should take advantage of Memory solution to speed up array processing, below is the code example, compare with TransposeArray function in your code.

(Sorry! I am Vietnamese, I use Google Translate to translate my words)

```VBA
Option Explicit
Option Private Module
#If VBA7 = 0 Then
   Private Enum LongLong:[_]:End Enum
#End If
#If Win64 = 0 Then
   Private Enum LongPtr:[_]:End Enum
#End If
Private Const nullptr As LongPtr = 0
Private Const vbLongPtr As Long = vbLong
#If Mac Then
  Private Const vbLongLong As Long = 20
#Else
  #If Win64 = 0 Then
    Private Const vbLongLong As Long = 20
  #End If
#End If
#If Win64 Then
Private Const PTR_SIZE& = 8
Private Const VAR_SIZE& = 24
#Else
Private Const PTR_SIZE& = 4
Private Const VAR_SIZE& = 16
#End If

Private Const STR_SIZE& = 4

#If VBA7 Then
  Private Declare PtrSafe Function VarPtrArray Lib "VBE7" Alias "VarPtr" (ByRef var() As Any) As LongPtr
#ElseIf VBA6 Then
  Private Declare PtrSafe Function VarPtrArray Lib "VBE6" Alias "VarPtr" (ByRef var() As Any) As Long
#Else
  Private Declare Function VarPtrArray Lib "VBA6" Alias "VarPtr" (ByRef var() As Any) As Long
#End If

#If VBA7 Then

  Private Declare PtrSafe Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As LongPtr)
  Private Declare PtrSafe Sub FillMemory Lib "kernel32" Alias "RtlFillMemory" (Destination As Any, ByVal Length As Long, ByVal Fill As Byte)
  Private Declare PtrSafe Sub MoveMemory Lib "kernel32.dll" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As LongPtr)
  Private Declare PtrSafe Sub ZeroMemory Lib "kernel32.dll" Alias "RtlZeroMemory" (Destination As Any, ByVal Length As LongPtr)
  Private Declare PtrSafe Function RtlCompareMemory Lib "ntdll" (ByVal ptrSource1 As LongPtr, ByVal ptrSource2 As LongPtr, ByVal Length As LongPtr) As Long
#Else
  Private Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As Long)
  Private Declare Sub FillMemory Lib "kernel32" Alias "RtlFillMemory" (Destination As Any, ByVal Length As Long, ByVal Fill As Byte)
  Private Declare Sub MoveMemory Lib "kernel32.dll" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As Long)
  Private Declare Sub ZeroMemory Lib "kernel32.dll" Alias "RtlZeroMemory" (Destination As Any, ByVal Length As Long)
  Private Declare Function RtlCompareMemory Lib "ntdll" (ByVal ptrSource1 As Long, ByVal ptrSource2 As Long, ByVal Length As Long) As Long
#End If

Private Const VT_BYREF As Long = &H4000&
Private Const S_OK As Long = &H0&

Private Type mmVar
  b(1 To VAR_SIZE) As Byte
End Type

Private Type SAFEARRAYBOUND
  cElements    As Long
  lLbound      As Long
End Type
Private Type SAFEARRAY
  cDims           As Integer
  fFeatures       As Integer
  cbElements      As Long
  cLocks          As Long
  pvData          As LongPtr
  rgsabound(1 To 2)  As SAFEARRAYBOUND
End Type


Function ArrayTranspose(ByRef srcArray As Variant, Optional rowBase1 As Integer = -1, Optional columnBase1 As Integer = -1) As Boolean
  If Not IsArray(srcArray) Then Exit Function
  Dim p As LongPtr, pA As LongPtr, Pb As LongPtr, pSA As LongPtr, t As LongPtr
  Dim s As SAFEARRAY, bo As SAFEARRAYBOUND, a() As mmVar, b() As mmVar
  Dim r&, c&, j3&, l1&, l2&, u1&, u2&
  pSA = VarPtr(srcArray) + PTR_SIZE: CopyMemory pSA, ByVal pSA, PTR_SIZE: CopyMemory s, ByVal pSA, LenB(s)
  If s.pvData = 0 Then Exit Function
  With s
    Select Case .cDims
    Case 2: With .rgsabound(2): l1 = .lLbound: u1 = .cElements + l1 - 1: End With
    End Select
    With .rgsabound(1): l2 = .lLbound: u2 = .cElements + l2 - 1: End With
  End With
  Select Case s.cDims
  Case 1
    t = (u2 - l2 + 1) * VAR_SIZE
    ReDim arr(l2 To u2, 1 To 1)
    p = VarPtr(srcArray(l2)): pA = VarPtr(arr(l2, 1))
    CopyMemory ByVal pA, ByVal p, t
    ZeroMemory ByVal p, t
    srcArray = arr
  Case 2:
    t = (u1 - l1 + 1) * (u2 - l2 + 1) * VAR_SIZE
    ReDim a(l1 To u1, l2 To u2): ReDim b(l2 To u2, l1 To u1)
    p = VarPtr(srcArray(l1, l2)): pA = VarPtr(a(l1, l2)): Pb = VarPtr(b(l2, l1))
    CopyMemory ByVal pA, ByVal p, t
    For r = l1 To u1: For c = l2 To u2: b(c, r) = a(r, c): Next c, r
    CopyMemory ByVal p, ByVal Pb, t
    With s
      bo = .rgsabound(1): .rgsabound(1) = .rgsabound(2): .rgsabound(2) = bo
      If rowBase1 > 0 Then .rgsabound(2).lLbound = rowBase1
      If columnBase1 > 0 Then .rgsabound(1).lLbound = columnBase1
    End With
    CopyMemory ByVal pSA, s, LenB(s)
    ZeroMemory ByVal Pb, t
  End Select
  ZeroMemory ByVal pA, t
  ArrayTranspose = True
End Function


Public Function GetArrayDimension(vArray As Variant) As Long
  Const VT_BYREF& = &H4000
  Dim lPtr As LongPtr
  If IsArray(vArray) Then
    lPtr = PeekPtr(VarPtr(vArray) + 8)
    If (PeekInt(VarPtr(vArray)) And VT_BYREF) <> 0 Then lPtr = PeekPtr(lPtr)
    If lPtr <> 0 Then GetArrayDimension = PeekInt(lPtr)
  End If
End Function

Private Function PeekPtr(ByVal lPtr As LongPtr) As LongPtr
  Call CopyMemory(PeekPtr, ByVal lPtr, LenB(lPtr))
End Function

Private Function PeekInt(ByVal lPtr As LongPtr) As Integer
  Call CopyMemory(PeekInt, ByVal lPtr, 2)
End Function
```

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

Thanks for your feedback. I do intend to rewrite this repository and take advantage of moving memory directly. However, that is precisely why I want to finish my [MemoryTools](https://github.com/cristianbuse/VBA-MemoryTools) libray first. There is a massive speed issue in VBA7 (not VBA6 or prior) when calling DLL APIs (like ```RtlMoveMemory```). It can be x600 times faster to use my memory library instead. 

I will update this library at some point but not his year for sure.

**Comment by SanbiVN** [comment]
Hi @cristianbuse!

I knew your [MemoryTools](https://github.com/cristianbuse/VBA-MemoryTools) library before!
Your library has many interested people.

I have a VBA Tools project, used to both learn and write VBA code, it makes me very proud and excited. If you are interested, I will translate it into English and share with you the final version which has many quite attractive functions for programmers.

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

>  I have a VBA Tools project, used to both learn and write VBA code, it makes me very proud and excited. If you are interested, I will translate it into English and share with you the final version which has many quite attractive functions for programmers.

Of course I would be interested to see new things but please don't go through the effort of translating just for me. if you are planning to share with everyone then I'd be happy to have a look.

Thanks!

**Comment by SanbiVN** [comment]
Hi @cristianbuse!

The VBA Tools project I shared a long time ago. But I have not updated the latest version to Github. Because I am Vietnamese, the ToolTip buttons in VB Tools are all in my mother tongue. It is very difficult for you to approach in the best way.

This is the project: [VBA_FastCode](https://github.com/SanbiVN/VBA_FastCode) 

(preview photo)
![image](https://github.com/cristianbuse/VBA-ArrayTools/assets/58664571/f678d807-2e06-4fc6-a40e-653546af1845)


What do you think I wrote an asynchronous UDF translation function, taking full advantage of Google Translate's 5000 character limit? Not only can you translate a single string, you can translate an entire array.

It only took me a few seconds to translate the entire caption and tooltip of the VBA Tools button. Here is it [GoogleTranslateXL](https://github.com/SanbiVN/GoogleTranslateXL/releases/tag/TranslateXL) 



You can safely wait for me to do it!

**Comment by SanbiVN** [comment]
Hi @cristianbuse!

Project VBA Tools, I have translated it, you can download my latest version.
Please download the version [VBA_FastCode.en_v2.2](https://github.com/SanbiVN/VBA_FastCode/releases/tag/fastcode) in English language.

The application I have uses Shell, CMD, HTTP, API, ... So the virus scanner will block it. You know how to download it, right?
I often use these two buttons to move through the procedure:
![image](https://github.com/cristianbuse/VBA-ArrayTools/assets/58664571/5b36a883-6d1c-42ec-a58a-c60c1e2d5e5c)

1. The button moves to the most recently manipulated line of code.
2. Navigate within the procedure: this feature helps move through parameters, variables, labels, and declarations quickly. (First, let's point the text at the object). This feature supports very long functions.

Many interesting things in my VBA Tools for you to explore!

After experiencing it, if you appreciate it, you can help me share it with everyone. I would be very grateful for that.

(Yesterday, I took advantage of your StateLossCallback class so VBA Tools doesn't lose state, Your idea is quite funny using the Clear event of the DataObject library)

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

Like you said, the antivirus detects malware/keygen so I cannot open the Excel files. If I have time in the next few weeks then I will look at the source code directly. Thanks!

**Comment by SanbiVN** [comment]
Hi @cristianbuse!

I will create a clean version soon, I will remove all the code that the scanner considers malicious, this will cause some buttons in VB Tools to no longer work. You will be able to download without being blocked by the scanner.

**Comment by SanbiVN** [comment]
Hi @cristianbuse!

I have removed all procedures and code related to the system and file operations.

[VBA_FastCode.EN_v2.2](https://github.com//SanbiVN/VBA_FastCode/releases/download/fastcode/VBA_FastCode.EN_v2.2.xlam)

![image](https://github.com/cristianbuse/VBA-ArrayTools/assets/58664571/e995f451-46ba-4243-b817-04c1826a06f3)

If you click on the button circled in red, the icon will become ticked.
Now when you click on the buttons, you will jump to the code lines of the executing procedure.

Strings in MsgBox are mostly Unicode strings.
Please forgive me because I have not translated the Unicode strings in the code into English.

**Comment by cristianbuse** [comment]
Hi @SanbiVN ,

Have you seen [Guido's string library](https://github.com/guwidoe/VBA-StringTools)?

It deals with Unicode easily and it's well written.

**Comment by SanbiVN** [comment]
Hi @cristianbuse

The project you proposed is very useful.

------------------------------------------
I'm writing a version of ```VBA_FastCode Tools``` for learning, the project's goal is for beginners to be able to learn VBA directly in the project without the need for books or trainers to teach VBA . Do you feel that is possible?

**Comment by cristianbuse** [comment]
@SanbiVN ,

It's possible but a lot of work.

**Comment by SanbiVN** [comment]
@cristianbuse

I will try with my current abilities. Achieving the desired result, I will share it on Github.
